pipelines:
  - name: check
    failure-message: Build failed. Leave a comment with 'metaplugin-recheck' to rerun a check.
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
          branch: ^master$
        - event: change-restored
          branch: ^master$
        - event: comment-added
          branch: ^master$
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*((metaplugin-recheck)|(recheck))\s*$
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: 0

projects:
  - name: openstack/neutron
    check:
      - gate-metaplugin
