- job:
    name: 'check-tempest-dsvm-metaplugin'
    description: 'Third-party testing for Neutron MetaPlugin'
    node: 'devstack_slave'

    wrappers:
      - timeout:
          timeout: 60  # Timeout in *minutes*
          fail: true   # A job run that exceeds the timeout will cause a failure
      - timestamps

    builders:
      - shell: |
          #!/bin/bash -x
          sudo rm -rf /opt/stack/logs
          # TODO: reduce cleanup range
          sudo rm -rf /opt/stack/new

          sudo ovs-vsctl --if-exists del-br br-int
          sudo ovs-vsctl --if-exists del-br br-ex
          sudo ovs-vsctl --if-exists del-br br-tun

          rm -rf devstack-gate
          ln -s /opt/devstack-gate
      - shell: |
          #!/bin/bash -xe
          export LANG=C
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST=1
          export ENABLED_SERVICES=metaplugin
          export DEVSTACK_GATE_FEATURE_MATRIX='/opt/metaplugin-ci/files/features.yaml'
          export DEVSTACK_GATE_TEMPEST_REGEX='tempest.api.network'

          function pre_test_hook {
              cp /opt/metaplugin-ci/files/neutron_thirdparty/metaplugin $BASE/new/devstack/lib/neutron_thirdparty/
          }
          export -f pre_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs  # In macros.yaml

    publishers:
      - devstack-logs  # In macros.yaml
      - console-log  # In macros.yaml
      - post-tasks:
          - matches:
              - log-text: ''
                operator: AND
            script: |
              bash /opt/metaplugin-ci/files/jenkins-slave.sh offline
              sudo /sbin/shutdown -r +1 &

- project:
    name: metaplugin-ci

    jobs:
        - check-tempest-dsvm-metaplugin:
