- job:
    name: 'check-tempest-dsvm-metaplugin'
    description: 'Third-party testing for Neutron MetaPlugin'
    node: 'devstack_slave'

    wrappers:
      - timeout:
          timeout: 185  # Timeout in *minutes*
          fail: true  # A job run that exceeds the timeout will cause a failure
      - timestamps

    builders:
      - shell: |
          #!/bin/bash -x
          ### TODO: log cleanup
          sudo ovs-vsctl --if-exists del-br br-int
          sudo ovs-vsctl --if-exists del-br br-ex
          sudo ovs-vsctl --if-exists del-br br-tun

          rm -rf devstack-gate
          ln -s /opt/devstack-gate
      - shell: |
          #!/bin/bash -xe
          export LANG=C
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST=1
          export ENABLED_SERVICES=metaplugin
          export SKIP_DEVSTACK_GATE_PROJECT=1
          export DEVSTACK_GATE_TEMPEST_REGEX='tempest.api.network'

          function pre_test_hook {
              cp /opt/metaplugin-ci/files/neutron_thirdparty/metaplugin $BASE/new/devstack/lib/neutron_thirdparty/
          }
          export -f pre_test_hook

          function gate_hook {
              remaining_time
              timeout -s 9 ${REMAINING_TIME}m /opt/devstack-gate/devstack-vm-gate.sh
          }
          export -f gate_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs  # In macros.yaml ### necessary ?
#
#    publishers:
#      - devstack-logs  # In macros.yaml
#      - devstack-confs # In macros.yaml
#      - console-log  # In macros.yaml

- project:
    name: metaplugin-ci

    jobs:
        - check-tempest-dsvm-metaplugin:
